env:
  node: true

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
